version: '3.8'

services:
  web:
    # L'image sera téléchargée depuis votre registre TechCorp par les serveurs distants
    image: registry.internal.techcorp.fr/techcorp-app:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://database:27017/techcorp_db
    depends_on:
      - database
    restart: always

  database:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: